install:
  - choco install gitversion.portable -pre -y
  
assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Debug

build_script:
  - cmd: nuget restore src/UnreleasedGitHubHistory.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo 
  - cmd: msbuild src/UnreleasedGitHubHistory.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%" 
  - cmd: appveyor PushArtifact "build\NuGetExeBuild\UnreleasedGitHubHistory.Portable.%GitVersion_NuGetVersion%.nupkg"

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified